FROM mcr.microsoft.com/devcontainers/python:dev-3.13-bookworm

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE=1

RUN mkdir -p /home/vscode/workspace/.venv \
    && chown -R vscode:vscode /home/vscode/workspace/.venv

WORKDIR /home/vscode/workspace
USER vscode

EXPOSE 8000
CMD ["/bin/bash"]

